name: Integration

on:
  push:
    branches:
      - master
      - develop
      - develop-v2
  pull_request:
    branches:
      - master
      - develop
      - develop-v2

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Compile TypeScript files
        run: npm run ts:build
      - name: Run tests
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
